version: '3.8'

services:
  # Serviço do Banco de Dados MongoDB
  mongo:
    image: mongo:latest
    container_name: Homolog
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      DATABASE_URL: "mongodb://admin:password@mongo:27017/"
    volumes:
      - mongo-data:/data/db
    networks:
      - academia-net

  # Serviço do Backend
  backend:
    build:
      context: ./academia_backend
      dockerfile: Dockerfile
    container_name: academia-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "mongodb://admin:password@mongo:27017/"
      DB_NAME: "academia"
      SECRET_KEY: "coloque_sua_chave_secreta_aqui"
    depends_on:
      - mongo
    networks:
      - academia-net

  # ---- SERVIÇO CORRIGIDO: WEBSITE ADMIN ----
  admin:
    build:
      # Aponta para a pasta correta da aplicação web
      context: ./academia-admin
      dockerfile: Dockerfile
    container_name: academia-admin-web
    restart: unless-stopped
    ports:
      # Mapeia a porta 8080 do seu PC para a porta 80 do Nginx
      - "8080:80"
    depends_on:
      - backend
    networks:
      - academia-net

volumes:
  mongo-data:
    driver: local

networks:
  academia-net:
    driver: bridge